import React from 'react';
import { categories } from '../data/categories';

const catMap = {};
categories.forEach(c => { catMap[c.id] = c; });

const VisualPlanExport = ({ planData, title, forwardRef }) => {
  return (
    <div 
      ref={forwardRef}
      style={{
        position: 'fixed', top: '-20000px', left: 0,
        width: '1200px', background: '#F8FAFC', padding: '60px',
        fontFamily: "'Outfit', sans-serif", color: '#1E293B',
        boxSizing: 'border-box'
      }}
    >
      <div style={{ textAlign: 'center', marginBottom: '60px' }}>
        <h1 style={{ fontSize: '64px', margin: '0 0 16px 0', color: '#6366F1' }}>✨ Kids Activities ✨</h1>
        <h2 style={{ fontSize: '36px', margin: 0, color: '#475569' }}>{title}</h2>
      </div>

      <div style={{ display: 'flex', flexDirection: 'column', gap: '40px' }}>
        {planData.map((dayPlan, i) => (
          <div key={i} style={{ background: '#FFF', borderRadius: '32px', padding: '40px', boxShadow: '0 10px 40px rgba(0,0,0,0.05)' }}>
            <h3 style={{ fontSize: '32px', margin: '0 0 30px 0', color: '#334155', borderBottom: '4px dashed #E2E8F0', paddingBottom: '16px' }}>
              📅 {dayPlan.dateStr}
            </h3>
            
            {dayPlan.activities.length === 0 ? (
              <p style={{ fontSize: '24px', color: '#94A3B8', fontStyle: 'italic' }}>No activities planned for today. Free play! 🎈</p>
            ) : (
              <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(280px, 1fr))', gap: '24px' }}>
                {dayPlan.activities.map((a, j) => {
                  const cat = catMap[a.category] || {};
                  return (
                    <div key={j} style={{
                      background: `${cat.color || '#94A3B8'}1A`, // 10% opacity
                      border: `4px solid ${cat.color || '#94A3B8'}`,
                      borderRadius: '24px', padding: '24px',
                      display: 'flex', flexDirection: 'column', alignItems: 'center', textAlign: 'center'
                    }}>
                      <div style={{ fontSize: '72px', marginBottom: '16px' }}>{cat.icon || '⭐'}</div>
                      <h4 style={{ fontSize: '24px', margin: '0 0 12px 0', color: '#1E293B' }}>{a.title}</h4>
                      <div style={{ display: 'flex', gap: '8px', flexWrap: 'wrap', justifyContent: 'center' }}>
                        <span style={{ background: '#FFF', padding: '6px 12px', borderRadius: '100px', fontSize: '16px', fontWeight: 'bold', color: '#64748B' }}>
                          ⏱ {a.duration}
                        </span>
                        <span style={{ background: '#FFF', padding: '6px 12px', borderRadius: '100px', fontSize: '16px', fontWeight: 'bold', color: '#64748B' }}>
                          👶 {a.ageRange}
                        </span>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>
        ))}
      </div>
      <div style={{ textAlign: 'center', marginTop: '60px', color: '#94A3B8', fontSize: '20px' }}>
        Generated by your Kids Activities Planner 🚀
      </div>
    </div>
  );
};

export default VisualPlanExport;
